### ISSUE TITLE
Error publishing library: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by sergiolecuona** [excalidraw/excalidraw-libraries#280]
Hi,

I'm trying to publish a new library with 91 elements and I'm getting a HTTP error 413 with the message: TypeError: Failed to fetch

If I export my library, file size 1,33MB. Is there any size limit or any limit on number of elements inside a library?

Thank you.
Regards.

**Comment by ad1992** [comment]
@sergiolecuona can you share your exported lib file so we can take a look ?

**Comment by sergiolecuona** [comment]
Yes, of course.

Thanks.

[awsicons.zip](https://github.com/excalidraw/excalidraw-libraries/files/7603812/awsicons.zip)
.

**Comment by dwelle** [comment]
@sergiolecuona yes, it's a size issue — but not due to the library size, rather the image preview size which in your case was around 40MB 😄. We'll deploy a fix tomorrow!

**Comment by dwelle** [comment]
@sergiolecuona should now be fixed. Note that we've also shipped support for `shift`-selecting library items, so all you have to do is `shift`-click on the first and the last item to select them all!

**Comment by sergiolecuona** [comment]
Great news! Thank you.

**Comment by sergiolecuona** [comment]
It still doesn't work for me. Now instead of error 413 I'm getting and error 500 when publishing the library :(

This request
 https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries/submit

Is answering with:
{"status":500,"name":"RequestError","message":"Oops... something went wrong!"}

**Comment by dwelle** [comment]
Looking into it.

**Comment by dwelle** [comment]
Should be fixed now, please try again!

**Comment by sergiolecuona** [comment]
Library Submitted! 
https://github.com/excalidraw/excalidraw-libraries/pull/285

Thank you very much for your quick response. Great job!
